version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  rabbit:
    image: "rabbitmq:alpine"
    ports: 
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=ruser
      - RABBITMQ_DEFAULT_PASS=rpwd
      - RABBITMQ_DEFAULT_VHOST=mvrabbit

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
     - "8080:8080"
    environment:
     - MW_REDIS=redis:6379
     - MW_RABBIT=amqp://ruser:rpwd@rabbit/mvrabbit
    command: /go/src/github.com/mhorr/mavencode-assignment/webserver/webserver
    depends_on:
      - rabbit
      - redis
    links:
     - rabbit
     - redis

  redisclient:
    build:
      context: .
      dockerfile: Dockerfile
    command: /go/src/github.com/mhorr/mavencode-assignment/redisclient/redisclient
    depends_on:
      - rabbit
      - redis
    links:
      - rabbit
      - redis
   
